# Generated by Django 4.1.3 on 2022-11-30 06:53

import assets.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_name', models.CharField(max_length=100, verbose_name='Asset Name')),
                ('asset_type', models.CharField(max_length=200, verbose_name='Asset Type')),
                ('asset_condition', models.CharField(choices=[('new', 'NEW'), ('used', 'USED')], max_length=50, null=True, verbose_name='Asset Condition')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=200, verbose_name='Address')),
                ('company_email', models.CharField(max_length=200, verbose_name='e-Mail')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(max_length=100, verbose_name='Name')),
                ('employee_designation', models.CharField(max_length=200, verbose_name='Designation')),
                ('employee_email', models.CharField(max_length=200, verbose_name='e-Mail')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.company', verbose_name=assets.models.Company)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('issue_date', models.DateTimeField(blank=True, verbose_name='Issue Date')),
                ('checkout_date', models.DateTimeField(verbose_name='checkout Date')),
                ('asset_return_condition', models.CharField(blank=True, choices=[('ok', 'Ok'), ('damaged', 'Damaged')], max_length=100, null=True, verbose_name='Asset Return Condition')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('asset', models.ManyToManyField(to='assets.assets', verbose_name='Asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.employee', verbose_name='Employee')),
            ],
        ),
    ]
